spring:
    main:
        web-application-type: servlet
    datasource:
        url: jdbc:mysql://localhost:3306/spring?serverTimezone=Asia/Seoul
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 1127star@
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: create
            use-new-id-generator-mappings: false
        show-sql: true
        properties:
            hibernate.format_sql: true
server:
    port: 3000
